# Generated by Django 5.0 on 2024-01-08 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspage',
            name='custom_title',
            field=models.CharField(help_text='Custom title for the blog detail page', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
