# Generated by Django 5.0 on 2024-01-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogspage_custom_title_alter_blogdetailpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspage',
            name='custom_title',
            field=models.CharField(help_text='Custom title for the blog detail page', max_length=100),
        ),
    ]
