# Generated by Django 5.0 on 2024-01-09 11:15

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_categoryorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.category'),
        ),
        migrations.DeleteModel(
            name='CategoryOrderable',
        ),
    ]
