# Generated by Django 5.0 on 2024-01-03 20:32

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Add additional text', required=True)), ('parg', wagtail.blocks.RichTextBlock(help_text='Add additional rich text', required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
